[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Headers para optimización y seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imágenes
[[headers]]
  for = "/*.{png,jpg,jpeg,gif,webp,avif,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Solo incluir redirects si tienes rutas específicas que necesiten manejo especial
# Para sitios estáticos de Astro, generalmente no necesitas redirects

# Configuración para formularios (si los necesitas)
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
# [build.processing.html]
#   pretty_urls = true
#   canonical_urls = true 